### ISSUE TITLE
Do we have performance benefit like https://github.com/amatsuda/jb ?

### ISSUE THREAD

**Issue by PikachuEXE** [malomalo/turbostreamer#10]
Copied from `jb`'s readme:
```
Jbuilder's partial + :collection internally calls array! method inside which _render_partial is called per each element of the given collection, and then it falls back to the view_context's render method.

So, for example if the collection has 100 elements, Jbuilder's render partial: performs render method 100 times, and so it calls find_template method (which is known as one of the heaviest parts of Action View) 100 times.

OTOH, Jb simply calls ActionView::PartialRenderer's render which is cleverly implemented to find_template only once beforehand, then pass each element to that template.
```

Edit: Seems hard to read here, use [this link](https://github.com/amatsuda/jb#why-is-jb-fast) if you want

Not sure if we have called `find_template` 100 times for 100 elements when rendering partial?

**Comment by malomalo** [comment]
Hmmm not sure I will investigate and maybe add jb performance test.

**Comment by malomalo** [comment]
I believe we do, I'm still not sure about what is going on in the Rails context yet, because w/o Rails I don't think we have this benefit.

**Comment by malomalo** [comment]
#13 will fix this. Thanks for pointing it out, none of the performance test showed it because it's only when using Rails with the Turbostreamer template handler.

**Comment by PikachuEXE** [comment]
Not sure why that PR will fix this
But I did look through the [source code for rendering collection](https://github.com/malomalo/turbostreamer/blob/master/lib/turbostreamer/template.rb#L115-L160)
And I can't find any performance issue (I don't use it anyway :P)
