### ISSUE TITLE
missing FROM-clause entry for table when adding json.cache!

### ISSUE THREAD

**Issue by gemp** [malomalo/turbostreamer#16]
There's something I struggle with for hours now.
I have a TurboStreamer template which works perfectly:

```ruby
# pools_controller.rb
class PoolsController < ApplicationController
  def index
    @users = User.includes(:roles).with_any_role(:admin, :previewer)
  end

# index.json.streamer
json.object! do
  json.users @users do |user|
    json.object! do
      json.extract! user, :id, :name, :email
        json.roles user.roles do |role| 
          json.object! do
            json.extract! role, :id, :name
          end
        end
      end
    end
  end
end
```

But as soon as I add caching:

```ruby
# index.json.streamer
json.object! do
  json.cache! @users do
    json.users @users do |user|
    ...
```

I have the error: `ActionView::Template::Error (PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "roles"`
It does that for any included table, not only for roles, with or without `.references()` at the end.
Strange thing is that I did a lot of other caching on TurboStreamer templates elsewhere in the app without any problem whatsoever...

Any idea?

**Comment by malomalo** [comment]
Interesting, do you mind uploading the stack trace?

Also note it might be faster in this situation to not cache since roles will already be in memory and caching may result in more network request

**Comment by gemp** [comment]
Honestly, I don't know how I can get a stack trace in the first place. But secondly, thanks fo your concern. Watching activity on this gem I never thought I would have an answer before months, so many thanks 😊

I used the roles example just to make it simple, I have evidently a lot more going on than caching roles. And when I switched from JBuilder to TurboStreamer I started without caching to simplify the transition. Everything went smoothly afterwards adding caching to many converted TurboStreamed views, f'n many thanks for that because it really speeded up things a lot. Except this one. I tried a lot of things before asking here... I really don't know what I can provide to help understand the problem.

**Comment by malomalo** [comment]
Uncomment the `Rails.backtrace_cleaner.remove_silencers!` line in `config/initializers/backtrace_silencers`. Then reproduce the bug and you should see the error and a bunch of lines after it, that's the stack trace that would help.

Glad your finding it useful! Didn't know other people had found it 🙂

**Comment by gemp** [comment]
Here's the log with stack trace: https://gist.github.com/gemp/3a2f552bf0468460a2eb44f66e479e28

As for how I found it it's your (unique) [StackOverflow response](https://stackoverflow.com/a/47613672/4681418) which led me to it. I was trying to find a way to improve, even a little, the JBuilder render (awful) speed and all I found needed to refactor with serializers, pretty harsh when you have those verbose JBuilder templates as legacy...

**Comment by malomalo** [comment]
I was able to recreate locally with this [gist](https://gist.github.com/malomalo/86048f4c2208ce4c388e9b69c89b6fe7).

Seems like it's an issue with Rail 5.1.6.2. Are you able to upgrade to Rails 5.2? If you modify the gist to Rails 5.2 it will work with the `.references(:roles)`.

If you are unable to upgrade add a `.joins(:roles)` and it will work.

As a side note if your caching relations in your views you might find [activerecord-cached_at](https://github.com/malomalo/activerecord-cached_at) useful.

**Comment by gemp** [comment]
Just a quick question about activerecord-cached_at which I find very interesting because it really bugged me to update a related record with touch just to see it re-cached. My question is why `cached_at` isn't more widely used? It seems so evident... I only started caching stuff so maybe it's a candid question.

**Comment by malomalo** [comment]
I always hated updating `updated_at` too because that is what we showed as last update to the record and touching it to blow cache gave a bunch of false `updated_at`s.

I'm not sure why people don't use `cached_at` more, maybe most people see it as an issue not worth fixing or doesn't cause to many issues for them?

We've been using cached_at in production for 5+ years, I can't imagine going back

**Comment by malomalo** [comment]
@gemp Did changing the Rails version or the `joins` work for you?

**Comment by gemp** [comment]
Be certain I'll keep this issue posted about that! I did the update though I had problems with dependencies and three open branches to manage — I'm also in the middle of a major refactoring and the "caching" branch is not a priority. BUT it seems I'm in Rails latest 5.2.4.3 now. Tomorrow is another day.

**Comment by gemp** [comment]
...

Works in Rails 5.2. Even without `.references()`...

😳😍😎

Now, can't wait to implement `cached_at`!

Thanks for your help!
