### ISSUE TITLE
Deprecation: Calling fragment_cache_key directly is deprecated in rails 5.2

### ISSUE THREAD

**Issue by PikachuEXE** [malomalo/turbostreamer#7]
DEPRECATION WARNING: Calling fragment_cache_key directly is deprecated and will be removed in Rails 6.0. All fragment accessors now use the combined_fragment_cache_key method that retains the key as an array, such that the caching stores can interrogate the parts for cache versions used in recyclable cache keys.

**Comment by malomalo** [comment]
Yes, we are in the process of upgrading to Rails 6 as well and I will trying to fix this in the next week or two so we can be ready to deploy Rails 6
